# -*- coding: utf-8 -*-
"""aa

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z_zopJlZcbaIxqU2Rmopb84Uq5I_uXg9
"""

!pip install google-generativeai streamlit

pip install --user google-generativeai streamlit

!python3 -m pip install google-generativeai streamlit

import subprocess
import sys

# Create and activate virtual environment
subprocess.run([sys.executable, "-m", "venv", "myenv"])
subprocess.run(["myenv/bin/activate"], shell=True)  # For macOS/Linux
# subprocess.run(["myenv\\Scripts\\activate"], shell=True)  # For Windows

# Install packages
subprocess.run([sys.executable, "-m", "pip", "install", "google-generativeai", "streamlit"])

import streamlit as st
import google.generativeai as genai

# Read API Key from file
file_path = "/content/api.txt"
with open(file_path, "r") as key_file:
    api_key = key_file.read().strip()

genai.configure(api_key=api_key)

# Initialize AI Model
model = genai.GenerativeModel("gemini-1.5-pro-latest")

st.title("💡 AI Tutor - Data Science Assistant")
st.chat_message("assistant").write("Good Day! Welcome to AI Tutor. Feel free to post your doubts!")

# Store chat history in session state
if "memory" not in st.session_state:
    st.session_state["memory"] = []

chat = model.start_chat(history=st.session_state["memory"])

# Display chat history
for msg in st.session_state["memory"]:
    st.chat_message("user").write(msg)

# User input
user_input = st.chat_input("Type your question...")

if user_input:
    st.chat_message("user").write(user_input)
    chat_response = chat.send_message(user_input)
    st.chat_message("ai").write(chat_response.text)







