# -*- coding: utf-8 -*-
"""AVV

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z_zopJlZcbaIxqU2Rmopb84Uq5I_uXg9
"""

import subprocess
import sys

# Function to install packages
def install_package(package):
    subprocess.check_call([sys.executable, "-m", "pip", "install", package])

# Install required packages
install_package("streamlit")
install_package("google-generativeai")

# Now import them
import streamlit as st
import google.generativeai as genai

# Configure Google API Key
file_path = '/content/api.txt'
with open(file_path, mode='r') as key:
    api = key.read()

genai.configure(api_key=api)

# Initialize AI Model
model = genai.GenerativeModel(model_name="gemini-1.5-pro-latest")

st.title("💡 AI Tutor - Data Science Assistant")
st.chat_message('assistant').write("Good Day! Welcome to AI Tutor. Feel free to post your doubts!")

# Store chat history in session state
if 'memory' not in st.session_state:
    st.session_state['memory'] = []

chat = model.start_chat(history=st.session_state['memory'])

# Display chat history
for msg in st.session_state['memory']:
    st.chat_message('user').write(msg)

# User input
user_input = st.chat_input("Type your question...")

if user_input:
    st.chat_message('user').write(user_input)
    chat_response = chat.send_message(user_input)
    st.chat_message('ai').write(chat_response.text)