# -*- coding: utf-8 -*-
"""DD

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z_zopJlZcbaIxqU2Rmopb84Uq5I_uXg9
"""

import streamlit as st
import google.generativeai as genai
import os
import subprocess
import sys

# Install dependencies if missing
def install_package(package):
    subprocess.run([sys.executable, "-m", "pip", "install", package], check=True)

try:
    import google.generativeai
except ImportError:
    install_package("google-generativeai")
    import google.generativeai

# Load API Key from a file
file_path = '/content/api.txt'  # Change this to your actual file location
if os.path.exists(file_path):
    with open(file_path, mode='r') as key:
        api_key = key.read().strip()
else:
    st.error("API key file not found!")
    st.stop()

# Configure API
genai.configure(api_key=api_key)
model = genai.GenerativeModel(model_name="gemini-1.5-pro-latest")

# Streamlit UI
st.title("💡 AI Chatbot Tutor")
st.write("Ask me anything about Data Science!")

# Chat history
if "messages" not in st.session_state:
    st.session_state["messages"] = []

for msg in st.session_state["messages"]:
    st.chat_message(msg["role"]).write(msg["content"])

user_input = st.chat_input("Type your question here...")

if user_input:
    st.session_state["messages"].append({"role": "user", "content": user_input})
    st.chat_message("user").write(user_input)

    try:
        response = model.generate_content(user_input)
        ai_response = response.text

        st.session_state["messages"].append({"role": "ai", "content": ai_response})
        st.chat_message("ai").write(ai_response)
    except Exception as e:
        st.error(f"⚠️ Error generating response: {e}")



