# -*- coding: utf-8 -*-
"""Dzx

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z_zopJlZcbaIxqU2Rmopb84Uq5I_uXg9
"""



import streamlit as st
import os
import sys
import subprocess

# Auto-install missing dependencies
def install_package(package):
    try:
        __import__(package)
    except ImportError:
        subprocess.run([sys.executable, "-m", "pip", "install", package], check=True)

install_package("google-generativeai")
import google.generativeai as genai

# Configure API Key
api_key_path = "/content/api.txt"  # Change to your actual path
if os.path.exists(api_key_path):
    with open(api_key_path, "r") as file:
        api_key = file.read().strip()
    genai.configure(api_key=api_key)
else:
    st.error("⚠️ API key file not found!")
    st.stop()

# Streamlit UI
st.title("💡 AI Chatbot Tutor")
st.write("Ask me anything about Data Science!")

if "messages" not in st.session_state:
    st.session_state["messages"] = []

for msg in st.session_state["messages"]:
    st.chat_message(msg["role"]).write(msg["content"])

user_input = st.chat_input("Type your question here...")

if user_input:
    st.session_state["messages"].append({"role": "user", "content": user_input})
    st.chat_message("user").write(user_input)

    try:
        model = genai.GenerativeModel(model_name="gemini-1.5-pro-latest")
        response = model.generate_content(user_input)
        ai_response = response.text

        st.session_state["messages"].append({"role": "ai", "content": ai_response})
        st.chat_message("ai").write(ai_response)
    except Exception as e:
        st.error(f"⚠️ Error generating response: {e}")